# @license AGPL-3.0-or-later
#
# Copyright(C) 2025 8 Hobbies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/alpine:3.21.2@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099

# Remove the community repository. This is to ensure that we only rely on
# packages with future availability.
RUN sed -i /community/d /etc/apk/repositories && cat /etc/apk/repositories

RUN apk add --no-cache git git-daemon

WORKDIR /srv/repos

RUN addgroup --system --gid 1001 git
RUN adduser --system --uid 1001 git
RUN chown git:git /srv/repos
USER git

RUN git config --global user.email "you@example.com" && \
    git config --global user.name "Your Name"

RUN mkdir single-branch && cd single-branch && \
    git init --initial-branch=trunk && \
    touch README && git add README && \
    GIT_COMMITTER_DATE="2025-01-18T00:00:00Z" git commit --date "2025-01-18T00:00:00Z" -m "Initial commit"

RUN mkdir double-branch && cd double-branch && \
    git init --initial-branch=default && \
    touch README && git add README && \
    GIT_COMMITTER_DATE="2025-01-19T11:11:11Z" git commit --date "2025-01-19T11:11:11Z" -m "Initial commit" && \
    git checkout -b feature && \
    echo "feature" >> README && git add README && \
    GIT_COMMITER_DATE="2025-01-20T22:22:22Z" git commit --date "2025-01-20T22:22:22Z" -m "feature"

EXPOSE 9418

ENTRYPOINT ["git", "daemon", "--export-all", "--reuseaddr", "--base-path=/srv/", "--informative-errors", "--verbose"]
