# @license AGPL-3.0-or-later
#
# Copyright(C) 2025 8 Hobbies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Dockerfile

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  DOCKER_CMD: docker

jobs:
  test:
    name: Dockerfile
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: "npm"

      - name: Build
        run: npm run build_container_img

      - name: Start the container
        run: npm run start_container

      - name: Install npm dependencies
        run: npm ci

      - name: Run test
        run: npm run test_live
